### ISSUE TITLE
hickory and other jsoup dependents are incompatible

### ISSUE THREAD

**Issue by port19x** [clj-easy/graalvm-clojure#61]
Idk where else to document this in a public manner.
Hickory, as well as most other projects labeling themselves as html parsers don't play nicely with graalvm.
This is because jsoup wants to be initialized at runtime and clojure libs at build time.
The project where I tried for days to get it to play with graal: [bbyt](https://github.com/port19x/bbyt)

**Comment by BrunoBonacci** [comment]
Hi @port19x,

It should be possible do initialize the subset of jsoup classes that need to be initialized at runtime.

Anyway, the starting point is to get the error and project to recreate it documented properly. In order to so please follow the instructions in the readme [How to contribute](https://github.com/clj-easy/graalvm-clojure#how-to-contribute) and will take it from there.
